import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { BenchEngine, replayExport } from './src/core/engine';
import { FileStorage } from './src/core/storage';

const dir = mkdtempSync(join(tmpdir(), 'dbg-'));
const engine = new BenchEngine(new FileStorage(dir), () => 2_000_000);
engine.createPartition('p0');
engine.createPartition('p1');
for (const [k,v] of [['a',1],['b',2],['a',3],['b',4]] as [string,number][]) engine.appendEvent('p0', k, v);
engine.appendEvent('p1','a',5); engine.appendEvent('p1','c',6);
engine.deployVersion(1);
engine.consumeBatch(3);
engine.checkpoint('manual');
engine.consumeBatch(10);
engine.checkpoint('manual');
const bundle = engine.exportExperiment();
console.log('exported', bundle.finalStateHash);
console.log('final ckpt progress', JSON.stringify(bundle.finalCheckpoint.progress));
console.log('final ckpt agg', JSON.stringify(bundle.finalCheckpoint.aggregates));
const rd = mkdtempSync(join(tmpdir(), 'dbg-r-'));
const res = replayExport(new FileStorage(rd), bundle);
console.log(res);
const re = new BenchEngine(new FileStorage(rd));
const c = re.storage.latestCheckpoint()!;
console.log('replay progress', JSON.stringify(c.data.progress));
console.log('replay agg', JSON.stringify(c.data.aggregates));
rmSync(dir,{recursive:true,force:true}); rmSync(rd,{recursive:true,force:true});
